### PR TITLE
XML:Track MSM8916:Display,Media,Audio

### PR DESCRIPTION
**Pull request by hpnightowl**
*These Are Creating Missing Shared Lib Error While Compiling For MSM8916 Devices

### CODE REVIEW

**Comment by IronSharpensIron2717** [comment]
Da FUQ!?

**Comment by hpnightowl** [comment]
what?

**Comment by IronSharpensIron2717** [comment]
Do you even Gerrit bro?

**Comment by hpnightowl** [comment]
ok got it :) i was not knowing that it has gerrit also

**Comment by NoSpamDan** [comment]
@hpnightowl This is not the place for help.  We don't have support for msm8916...

**Comment by hpnightowl** [comment]
ok @NoSpamDan

**Pull request closed without merging**
